package sorts;

import partitions.*;

public class QuickSort extends Sort
{
	
	// per sort swap counter
	private long swapsLastSort = 0;
	
	// the partition technique
	private Partition partitioner;
	
	// constructor
	public QuickSort(Partition partitionMethod)
	{
		partitioner = partitionMethod;
	}
	
	// in case this wasn't done during instantiation
	public void setPartitionTechnique(Partition partitionMethod)
	{
		partitioner = partitionMethod;
	}
	
	public long getSwapsLastSort()
	{
		if (partitioner != null) {
			return swapsLastSort;
		} else {
			return -1;
		}
	}
	
	// returns the number of swaps generated by this sorting routine - or returns -1 if the partitioner was never instantiated
	public long getTotalSwaps()
	{
		if (partitioner != null) {
			return partitioner.getTotalSwaps();
		} else {
			return -1;
		}
	}
	
	// implements QuickSort and uses partitioner.partition()
	private void quickSort(int[] A, int M, int N)
	{
		int[] refIndeces = new int[2];
		if (M < N) {
			partitioner.partition(A, M, N, refIndeces);
			// increment the basic operation per each partition and add to the per-sort swaps
			incBasicOpCount();
			swapsLastSort += partitioner.getSwapsLastPartition();
			// recursively quickSort
			quickSort(A, M, refIndeces[0]);
			quickSort(A, refIndeces[1], N);
		}
	}
	
	// concrete sort method
	@Override
	public void sort(int[] data)
	{
		resetBasicOpCount();
		swapsLastSort = 0;
		if (partitioner != null) {
			partitioner.resetTotalBasicOpCount();
			quickSort(data, 0, data.length - 1);
			addToOpCount(partitioner.getTotalBasicOpCount());
			addToTotalOpCount(getBasicOpCountLastSort());
		} else {
			System.out.println("No partition method was set!");
		}
	}

	@Override
	public String getSortName()
	{
		return "Quicksort (" + partitioner.getPartitionerName() + ")";
	}
}
