package sorts;

import partitions.*;

public class QuickSort extends Sort
{
	// the partition technique
	private Partition partitioner;
	
	// constructor
	public QuickSort(Partition partitionMethod)
	{
		partitioner = partitionMethod;
	}
	
	// in case this wasn't done during instantiation
	public void setPartitionTechnique(Partition partitionMethod)
	{
		partitioner = partitionMethod;
	}
	
	// returns the number of swaps generated by this sorting routine - or returns -1 if the partitioner was never instantiated
	public long getTotalSwaps()
	{
		if (partitioner != null) {
			return partitioner.getTotalSwaps();
		} else {
			return -1;
		}
	}
	
	// concrete sort method
	public void sort(int[] data)
	{
		if (partitioner != null) {
			quickSort(data, 0, data.length - 1);
		} else {
			System.out.println("No partition method was set!");
		}
	}
	
	// implements QuickSort and uses partitioner.partition()
	private void quickSort(int[] A, int M, int N)
	{
		int[] refIndeces = new int[2];
		if (M < N) {
			partitioner.partition(A, M, N, refIndeces);
			quickSort(A, M, refIndeces[0]);
			quickSort(A, refIndeces[1], N);
		}
	}
}
